### ISSUE TITLE
startServer.bat error

### ISSUE THREAD

**Issue by mxze** [kavezo/MagiReco_NA_Server#18]
Sorry, it's me again!
Getting an error with the latest version-I complete the instructions successfully all up until running startServer.bat. The second window that pops up reads the following out to me and immediately closes:
<pre><code>Traceback (most recent call last):
File "gevent_server.py", line 5, in &lt;module&gt;
File "&lt;frozen_importlib._bootstrap&gt;", line 991, in _find_and_load
File "&lt;frozen importlib._bootstrap&gt;", line 975, in _find_and_load_unlocked
File "&lt;frozen importlib._bootstrap&gt;", line 671, in _load_unlocked
File "d:\0w0\magireco\na_server_flask\zipzap\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "dnserver.py", line 7, in &lt;module&gt;
socket.gaierror: [Errno 11001] getaddrinfo failed
[716] Failed to execute script gevent_server
</code></pre>
As far as I can tell the private server is unable to boot up from there. The first window that popped up just reads out:
<code>nginx version: nginx/1.19.4</code>
and nothing more.

**Comment by kavezo** [comment]
ooof, it must be https://github.com/kavezo/ZipZap/blob/https/dnserver.py#L7... that method of retrieving someone's local address must fail on some computers

I'll check to see if there's a better way to do it

**Comment by SuzukaGozen** [comment]
This looks like a good way https://stackoverflow.com/a/166589

**Comment by mxze** [comment]
Alright, so I thiiiiiink the latest version has fixed this problem? I don't get the initial error I described and now nginx seems to boot up with it saying app server and dns server have both started. However I'm running into a new problem but I'll make a new post about that I suppose, sorry for spamming your issues forum!!
