### ISSUE TITLE
Error when transferring over old user data

### ISSUE THREAD

**Issue by mxze** [kavezo/MagiReco_NA_Server#37]
The newer versions seem to be working fine until I transfer over my user data, then I get an error upon running startServer.bat. I've tested to make sure it works with the default user data and it does so I think it must be something with one of the files in my user data.
<pre><code>nginx version: nginx/1.19.4
Traceback (most recent call last):
  File "gevent_server.py", line 2, in &ltmodule>
  File "&ltfrozen importlib._bootstrap>", line 991, in _find_and_load
  File "&ltfrozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "&ltfrozen importlib._bootstrap>", line 671, in _load_unlocked
  File "d:\0w0\magireco\na_server_flask\zipzap\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "app.py", line 13, in <module>
  File "&ltfrozen importlib._bootstrap>", line 991, in _find_and_load
  File "&ltfrozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "&ltfrozen importlib._bootstrap>", line 671, in _load_unlocked
  File "d:\0w0\magireco\na_server_flask\zipzap\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "api\arena.py", line 6, in <module>
  File "&ltfrozen importlib._bootstrap>", line 991, in _find_and_load
  File "&ltfrozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "&ltfrozen importlib._bootstrap>", line 671, in _load_unlocked
  File "d:\0w0\magireco\na_server_flask\zipzap\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "util\dataUtil.py", line 47, in &ltmodule&gt;
  File "util\dataUtil.py", line 20, in createIndex
  File "util\dataUtil.py", line 23, in createIndexFromList
  File "util\dataUtil.py", line 23, in &ltdictcomp>
  File "util\dataUtil.py", line 7, in &ltlambda>
TypeError: 'NoneType' object is not subscriptable
[8780] Failed to execute script gevent_server</pre></code>

**Comment by kavezo** [comment]
interesting...do you have a copy of your userItemList I could look at?
Or, there must be some nulls in the list rather than actual userItem objects -- I think if you delete those it should be fine.
Not sure how they came up, I hope we fixed the bug that caused them :[

**Comment by mxze** [comment]
Here's my copy--I couldn't really tell from looking at it if there was anything wrong with it.
[userItemList.zip](https://github.com/kavezo/ZipZap/files/5612708/userItemList.zip)

**Comment by kavezo** [comment]
It looks like there was a null at the very end of the list. I took it out and it was able to work...let me know if this works for you.
[userItemList.zip](https://github.com/kavezo/ZipZap/files/5612790/userItemList.zip)

**Comment by mxze** [comment]
AHHHH okay my bad, I wasn't completely certain what to look for and didn't know if that was in there previously or not..thank you though! I'm not sure as to what caused it as I had edited the file before but just to add amounts of items. If it appears again I'll try to keep track of what I was doing recently in the game to see if I can find a cause, but for now I at least know how to fix it if I get that error again. Thank you!!
