### ISSUE TITLE
.

### ISSUE THREAD

**Issue by KenZync** [kavezo/MagiReco_NA_Server#54]
.

**Comment by KenZync** [comment]
i tried to put data inside and it still error someting else

```
D:\ZipZap\windows\gevent_server>gevent_server.exe
Traceback (most recent call last):
  File "gevent_server.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "d:\0w0\magireco\na_server_flask\zipzap\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "app.py", line 18, in <module>
  File "util\homuUtil.py", line 201, in startCron
  File "util\homuUtil.py", line 183, in changeLogName
TypeError: 'NoneType' object is not subscriptable
[9084] Failed to execute script gevent_server
```

**Comment by KenZync** [comment]
I guess python must be 3.8?
